### ISSUE TITLE
/acceptance/checkNote API method

### ISSUE THREAD

**Issue by kushti** [ChainCashLabs/chaincash-rs#51]
make an API method which is getting a JSON encoded note via POST and returns whether it can be accepted or not

**Comment by prerak01** [comment]
hello 

I hope you are well. could I please work on this issue ?

Wanted to ask for sample input and output for this please

**Comment by kushti** [comment]
Hi, yes , any help needed ? Sorry for the long reply, traveling a bit now

**Comment by prerak01** [comment]
no problem. I am trying this out .

**Comment by prerak01** [comment]
Hello
I apologize if this is a beginner question but when I try to run locally, I get the following error. Looks like it is trying to connect to a port. Am I supposed to run  some other software alongside this? I am using ubuntu 22 on WSL
`prera@LAPTOP-3A8IOK1A:~/workspace/generic-work/chaincash-rs$ cargo run -- run 
warning: associated function `delete_with_conn` is never used
  --> crates/chaincash_store/src/ergo_boxes.rs:81:19
   |
52 | impl ErgoBoxRepository {
   | ---------------------- associated function in this implementation
...
81 |     pub(crate) fn delete_with_conn(conn: &mut ConnectionType, box_id: BoxId) -> Result<(), Error> {
   |                   ^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: `chaincash_store` (lib) generated 1 warning
warning: trait `AsStatusCode` is never used
  --> crates/chaincash_server/src/api.rs:10:7
   |
10 | trait AsStatusCode {
   |       ^^^^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: `chaincash_server` (lib) generated 1 warning
warning: use of deprecated type alias `std::panic::PanicInfo`: use `PanicHookInfo` instead
  --> crates/chaincash_cli/src/main.rs:70:5
   |
70 |     human_panic::setup_panic!();
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(deprecated)]` on by default
   = note: this warning originates in the macro `$crate::setup_panic` which comes from the expansion of the macro `human_panic::setup_panic` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: use of deprecated type alias `std::panic::PanicInfo`: use `PanicHookInfo` instead
  --> crates/chaincash_cli/src/main.rs:70:5
   |
70 |     human_panic::setup_panic!();
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this warning originates in the macro `$crate::setup_panic` which comes from the expansion of the macro `human_panic::setup_panic` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: `chaincash_cli` (bin "chaincash_cli") generated 2 warnings
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 2.04s
     Running `target/debug/chaincash_cli run`
2025-07-13T11:21:08.993677Z  INFO chaincash_cli: started with Cli { command: Run, log_level: Level(Info) }
2025-07-13T11:21:09.027452Z  INFO chaincash_app: loaded 1 predicates from files
thread 'main' panicked at /home/prera/workspace/generic-work/chaincash-rs/crates/chaincash_app/src/lib.rs:91:44:
called `Result::unwrap()` on an `Err` value: NodeError(Http(reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("localhost")), port: Some(9053), path: "/scan/listAll", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })) }))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
prera@LAPTOP-3A8IOK1A:~/workspace/generic-work/chaincash-rs$ `

**Comment by prerak01** [comment]
Just wanted to confirm this. I will need to run a full node to test out this server , right? I get errors when I try to run it using a light node

**Comment by prerak01** [comment]
Hello . 
I am sorry if this is a beginner issue but needed some help. I have a an ergo node running locally on http://localhost:9053 . I try to run the chaincash server on Ubuntu 22 WSL but I am getting errors and it is not starting up.
```
prera@LAPTOP-3A8IOK1A:~/workspace/generic-work/chaincash-rs$ RUST_BACKTRACE=1 cargo run -- run 
warning: associated function `delete_with_conn` is never used
  --> crates/chaincash_store/src/ergo_boxes.rs:81:19
   |
52 | impl ErgoBoxRepository {
   | ---------------------- associated function in this implementation
...
81 |     pub(crate) fn delete_with_conn(conn: &mut ConnectionType, box_id: BoxId) -> Result<(), Error> {
   |                   ^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: `chaincash_store` (lib) generated 1 warning
warning: trait `AsStatusCode` is never used
  --> crates/chaincash_server/src/api.rs:10:7
   |
10 | trait AsStatusCode {
   |       ^^^^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: `chaincash_server` (lib) generated 1 warning
warning: use of deprecated type alias `std::panic::PanicInfo`: use `PanicHookInfo` instead
  --> crates/chaincash_cli/src/main.rs:70:5
   |
70 |     human_panic::setup_panic!();
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(deprecated)]` on by default
   = note: this warning originates in the macro `$crate::setup_panic` which comes from the expansion of the macro `human_panic::setup_panic` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: use of deprecated type alias `std::panic::PanicInfo`: use `PanicHookInfo` instead
  --> crates/chaincash_cli/src/main.rs:70:5
   |
70 |     human_panic::setup_panic!();
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this warning originates in the macro `$crate::setup_panic` which comes from the expansion of the macro `human_panic::setup_panic` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: `chaincash_cli` (bin "chaincash_cli") generated 2 warnings
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.21s
     Running `target/debug/chaincash_cli run`
2025-07-15T16:58:59.905271Z  INFO chaincash_cli: started with Cli { command: Run, log_level: Level(Info) }
2025-07-15T16:58:59.908150Z  INFO chaincash_app: loaded 1 predicates from files
thread 'main' panicked at /home/prera/workspace/generic-work/chaincash-rs/crates/chaincash_app/src/lib.rs:91:44:
called `Result::unwrap()` on an `Err` value: NodeError(BadRequest("The request content was malformed:\nAttempt to decode value on failed cursor: DownField(treeVersion)"))
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e71f9a9a98b0faf423844bf0ba7438f29dc27d58/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/e71f9a9a98b0faf423844bf0ba7438f29dc27d58/library/core/src/panicking.rs:76:14
   2: core::result::unwrap_failed
             at /rustc/e71f9a9a98b0faf423844bf0ba7438f29dc27d58/library/core/src/result.rs:1699:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/e71f9a9a98b0faf423844bf0ba7438f29dc27d58/library/core/src/result.rs:1104:23
   4: chaincash_app::ChainCashApp::run::{{closure}}
             at ./crates/chaincash_app/src/lib.rs:91:9
   5: chaincash_cli::Cli::execute::{{closure}}
             at ./crates/chaincash_cli/src/main.rs:62:81
   6: chaincash_cli::main::{{closure}}
             at ./crates/chaincash_cli/src/main.rs:72:28
   7: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /home/prera/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.1/src/runtime/park.rs:281:63
   8: tokio::runtime::coop::with_budget
             at /home/prera/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.1/src/runtime/coop.rs:107:5
   9: tokio::runtime::coop::budget
             at /home/prera/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.1/src/runtime/coop.rs:73:5
  10: tokio::runtime::park::CachedParkThread::block_on
             at /home/prera/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.1/src/runtime/park.rs:281:31
  11: tokio::runtime::context::blocking::BlockingRegionGuard::block_on
             at /home/prera/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.1/src/runtime/context/blocking.rs:66:9
  12: tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}
             at /home/prera/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.1/src/runtime/scheduler/multi_thread/mod.rs:87:13
  13: tokio::runtime::context::runtime::enter_runtime
             at /home/prera/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.1/src/runtime/context/runtime.rs:65:16
  14: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /home/prera/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.1/src/runtime/scheduler/multi_thread/mod.rs:86:9
  15: tokio::runtime::runtime::Runtime::block_on
             at /home/prera/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.1/src/runtime/runtime.rs:349:45
  16: chaincash_cli::main
             at ./crates/chaincash_cli/src/main.rs:72:5
  17: core::ops::function::FnOnce::call_once
             at /rustc/e71f9a9a98b0faf423844bf0ba7438f29dc27d58/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
prera@LAPTOP-3A8IOK1A:~/workspace/generic-work/chaincash-rs$ 
```

**Comment by prerak01** [comment]
I got it. the chaincash server does not work with latest node version (I was using 6.0.0) . Now I downgraded to 5.0.24 and it is working
